config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :notes

  authenticated :user do
    root 'notes#index', as: "authenticated_root"
  end
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :find_note , only: [:show, :edit, :update, :destroy]
    
    def index
        @note=Note.where(user_id: current_user)
    end

    def show
    end

    def new
        @note=current_user.notes.build
    end

    def create
        @note=current_user.notes.build(note_params)
        if @note.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @note.update(note_params)
            redirect_to @note
        else
            render 'new'
        end
    end

    def destroy
        @note.destroy
        redirect_to notes_path
    end

    private
    
    def find_note
        @note=Note.find(params[:id])
    end

    def note_params
        params.require(:note).permit(:title,:content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notesapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
  </head>

  <body>
  <!--
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  -->
  <div>
    <nav>
    <%= link_to image_tag('logo.jpeg',  :size => '200x200'), root_path , id: "logo"  %>
    <% if user_signed_in? %>
      <%=  link_to "New Note" ,new_note_path  , class: "nav-links1" %>
      <%=  link_to "Sign Out", destroy_user_session_path ,method: :delete , class: "nav-links2"  %>
    <% else %>
      <%=  link_to "Log in", new_user_session_path , class: "nav-links3"  %>
      <%=  link_to "Sign Up", new_user_registration_path , class: "nav-links4" %>
    <%end %>
    </nav>
    <%=yield%>
  </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for @note , html: { multipart: true } do |f| %>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br>
	<br>
	<%= f.label :content %><br>
	<%= f.text_area :content %><br>
	<br>
	<%= f.submit  %>
    <%= link_to  "Cancel", notes_path %>
<% end %>

app/views/notes/edit.html.erb
<h3>Edit note<i class="fa fa-pencil"></i></h3>
<%=render 'form' %>

app/views/notes/index.html.erb
<% @note.each do |note| %>
<h1><%=note.title%></h1>
<p>
<%=time_ago_in_words(note.created_at)%>
<div>
<p><%= note.content %></p>
<%=link_to "Delete note", note_path(note),method: :delete, data: {confirm: "Are you sure?"}%>
<%= link_to  "Edit Note",edit_note_path(note) %>
</div>
<%end%>

app/views/notes/new.html.erb
<h3>Add a new note</h3>
<%=render 'form' %>

app/views/notes/show.html.erb
<%
=begin%>
 <%= link_to  "Home", notes_path %> 
<%
=end%>
<h1><%= @note.title %></h1>
<div>
<p><%= @note.content %></p>
</div>

app/views/welcome/index.html.haml
#banner
    .banner_content
    %h1 NotesApp
    %p Online Notebook
    %button= link_to "Sign Up" ,new_user_registration_path

#motto
    .wrapper
        %p.quote= "Your custom notes app"
        %p.name= "admin"